title: "Herky Hack"
url: "http://herkyhack.com"

podcast_dir: "_episodes"

collections:
  episodes:
    output: true

defaults:
  - scope:
      path: _episodes
    values:
      layout: page

exclude:
  - "*.md"
  - "Gemfile*"
